#include <rex/ppc/context.h>

#include <atomic>

#include <rex/logging.h>

#define DEFINE_IMPORT_SHIM(name) \
  PPC_FUNC_IMPL(__imp__##name) { (void)ctx; (void)base; }

DEFINE_IMPORT_SHIM(EtxProducerLog)
DEFINE_IMPORT_SHIM(EtxProducerRegister)
DEFINE_IMPORT_SHIM(EtxProducerUnregister)
DEFINE_IMPORT_SHIM(IoCheckShareAccess)
DEFINE_IMPORT_SHIM(IoCompleteRequest)
DEFINE_IMPORT_SHIM(IoDeleteDevice)
DEFINE_IMPORT_SHIM(IoDismountVolume)
DEFINE_IMPORT_SHIM(IoInvalidDeviceRequest)
DEFINE_IMPORT_SHIM(IoRemoveShareAccess)
DEFINE_IMPORT_SHIM(IoSetShareAccess)
DEFINE_IMPORT_SHIM(KeInitializeMutant)
DEFINE_IMPORT_SHIM(KeReleaseMutant)
DEFINE_IMPORT_SHIM(KeRestoreFloatingPointState)
DEFINE_IMPORT_SHIM(KeSaveFloatingPointState)
DEFINE_IMPORT_SHIM(LDICreateDecompression)
DEFINE_IMPORT_SHIM(LDIDecompress)
DEFINE_IMPORT_SHIM(LDIDestroyDecompression)
DEFINE_IMPORT_SHIM(NetDll_getpeername)
DEFINE_IMPORT_SHIM(NetDll_getsockname)
DEFINE_IMPORT_SHIM(NetDll_getsockopt)
DEFINE_IMPORT_SHIM(NetDll_WSACancelOverlappedIO)
DEFINE_IMPORT_SHIM(NetDll_WSAEventSelect)
DEFINE_IMPORT_SHIM(NetDll_WSAGetOverlappedResult)
DEFINE_IMPORT_SHIM(NetDll_WSARecv)
DEFINE_IMPORT_SHIM(NetDll_WSASend)
DEFINE_IMPORT_SHIM(NetDll_XNetConnect)
DEFINE_IMPORT_SHIM(NetDll_XNetCreateKey)
DEFINE_IMPORT_SHIM(NetDll_XNetGetConnectStatus)
DEFINE_IMPORT_SHIM(NetDll_XNetQosLookup)
DEFINE_IMPORT_SHIM(NetDll_XNetRegisterKey)
DEFINE_IMPORT_SHIM(NetDll_XNetServerToInAddr)
DEFINE_IMPORT_SHIM(NetDll_XNetUnregisterInAddr)
DEFINE_IMPORT_SHIM(NetDll_XNetUnregisterKey)
DEFINE_IMPORT_SHIM(NtCancelIoFile)
DEFINE_IMPORT_SHIM(NtWriteFileGather)
DEFINE_IMPORT_SHIM(ObCreateObject)
DEFINE_IMPORT_SHIM(ObIsTitleObject)
DEFINE_IMPORT_SHIM(ObReferenceObject)
DEFINE_IMPORT_SHIM(PsCamDeviceRequest)
DEFINE_IMPORT_SHIM(RtlUpcaseUnicodeChar)
DEFINE_IMPORT_SHIM(XamCacheCloseFile)
DEFINE_IMPORT_SHIM(XamCacheOpenFile)
DEFINE_IMPORT_SHIM(XamCacheReset)
DEFINE_IMPORT_SHIM(XamGetActiveDashAppInfo)
DEFINE_IMPORT_SHIM(XamInputRawState)
DEFINE_IMPORT_SHIM(XamNuiCameraElevationGetAngle)
DEFINE_IMPORT_SHIM(XamNuiCameraElevationSetAngle)
DEFINE_IMPORT_SHIM(XamNuiCameraElevationStopMovement)
DEFINE_IMPORT_SHIM(XamNuiCameraRememberFloor)
DEFINE_IMPORT_SHIM(XamNuiCameraTiltGetStatus)
DEFINE_IMPORT_SHIM(XamNuiCameraTiltReportStatus)
DEFINE_IMPORT_SHIM(XamNuiCameraTiltSetCallback)
DEFINE_IMPORT_SHIM(XamNuiIdentityGetSessionId)
DEFINE_IMPORT_SHIM(XamProfileCreateEnumerator)
DEFINE_IMPORT_SHIM(XamProfileEnumerate)
DEFINE_IMPORT_SHIM(XamReadBiometricData)
DEFINE_IMPORT_SHIM(XamShowAchievementsUI)
DEFINE_IMPORT_SHIM(XamShowFriendsUI)
DEFINE_IMPORT_SHIM(XamShowGameInviteUI)
DEFINE_IMPORT_SHIM(XamShowGamerCardUIForXUID)
DEFINE_IMPORT_SHIM(XamShowMarketplaceDownloadItemsUI)
DEFINE_IMPORT_SHIM(XamShowMarketplaceUI)
DEFINE_IMPORT_SHIM(XamShowNuiDeviceSelectorUI)
DEFINE_IMPORT_SHIM(XamShowNuiGuideUI)
DEFINE_IMPORT_SHIM(XamShowNuiMessageBoxUI)
DEFINE_IMPORT_SHIM(XamShowNuiSigninUI)
DEFINE_IMPORT_SHIM(XamShowPlayersUI)
DEFINE_IMPORT_SHIM(XamUserGetAgeGroup)
DEFINE_IMPORT_SHIM(XamUserGetIndexFromXUID)
DEFINE_IMPORT_SHIM(XamUserGetMembershipTierFromXUID)
DEFINE_IMPORT_SHIM(XamUserGetOnlineCountryFromXUID)
DEFINE_IMPORT_SHIM(XamUserNuiEnableBiometric)
DEFINE_IMPORT_SHIM(XamUserNuiGetEnrollmentIndex)
DEFINE_IMPORT_SHIM(XamUserNuiGetUserIndex)
DEFINE_IMPORT_SHIM(XamVoiceSubmitPacket)
DEFINE_IMPORT_SHIM(XamWriteBiometricData)
DEFINE_IMPORT_SHIM(XamXlfsInitializeUploadQueue)
DEFINE_IMPORT_SHIM(XamXlfsMountUploadQueueInstance)
DEFINE_IMPORT_SHIM(XamXlfsUninitializeUploadQueue)
DEFINE_IMPORT_SHIM(XamXlfsUnmountUploadQueueInstance)
DEFINE_IMPORT_SHIM(XamXStudioRequest)
DEFINE_IMPORT_SHIM(XAudioGetDuckerAttackTime)
DEFINE_IMPORT_SHIM(XAudioGetDuckerHoldTime)
DEFINE_IMPORT_SHIM(XAudioGetDuckerLevel)
DEFINE_IMPORT_SHIM(XAudioGetDuckerReleaseTime)
DEFINE_IMPORT_SHIM(XAudioGetDuckerThreshold)
DEFINE_IMPORT_SHIM(XCustomGetCurrentGamercard)
DEFINE_IMPORT_SHIM(XCustomGetLastActionPressEx)
DEFINE_IMPORT_SHIM(XCustomSetDynamicActions)
DEFINE_IMPORT_SHIM(XCustomUnregisterDynamicActions)
DEFINE_IMPORT_SHIM(XeCryptSha384Final)
DEFINE_IMPORT_SHIM(XeCryptSha384Init)
DEFINE_IMPORT_SHIM(XeCryptSha384Update)
DEFINE_IMPORT_SHIM(XeCryptSha512Final)
DEFINE_IMPORT_SHIM(XeCryptSha512Init)
DEFINE_IMPORT_SHIM(XeCryptSha512Update)
DEFINE_IMPORT_SHIM(XeKeysGetConsoleID)
DEFINE_IMPORT_SHIM(XNetLogonGetMachineID)
DEFINE_IMPORT_SHIM(XNetLogonGetTitleID)

PPC_FUNC_IMPL(__imp__NtQueryVolumeInformationFile_shim) {
  static constexpr uint32_t kStatusNotSupported = 0xC00000BBu;
  const uint32_t io_status_block_ptr = ctx.r4.u32;
  if (io_status_block_ptr) {
    PPC_STORE_U32(io_status_block_ptr + 0, kStatusNotSupported);
    PPC_STORE_U32(io_status_block_ptr + 4, 0);
  }
  static std::atomic<uint32_t> s_counter{0};
  const uint32_t call_num = ++s_counter;
  if (call_num <= 5) {
    REXKRNL_WARN("__imp__NtQueryVolumeInformationFile_shim [#{}] returning STATUS_NOT_SUPPORTED", call_num);
  }
  ctx.r3.u64 = kStatusNotSupported;
}
