// forza_horizon_1 - ReXGlue Recompiled Project
// Generated by: rexglue init
//
// This file is SDK-managed. Customizations go in virtual hook overrides.
// Running 'rexglue migrate' will overwrite this file.

#include "generated/forza_horizon_1_config.h"
#include "generated/forza_horizon_1_init.h"

#include <cstdlib>
#include <filesystem>
#include <rex/filesystem.h>
#include <rex/input/input_system.h>
#include <rex/input/nop/nop_input_driver.h>
#include <rex/logging.h>
#include <rex/rex_app.h>
#include <rex/system/kernel_state.h>
#include <rex/system/user_module.h>

namespace {
const bool kDisableSdlWgi = []() {
  _putenv_s("SDL_JOYSTICK_WGI", "0");
  return true;
}();
}

class ForzaHorizon1App : public rex::ReXApp {
 public:
  using rex::ReXApp::ReXApp;

  static std::unique_ptr<rex::ui::WindowedApp> Create(
      rex::ui::WindowedAppContext& ctx) {
    return std::unique_ptr<ForzaHorizon1App>(new ForzaHorizon1App(ctx, "forza_horizon_1",
        {PPC_CODE_BASE, PPC_CODE_SIZE, PPC_IMAGE_BASE,
         PPC_IMAGE_SIZE, PPCFuncMappings}));
  }

 protected:
  void OnConfigurePaths(rex::PathConfig& paths) override {
    const auto exe_folder = rex::filesystem::GetExecutableFolder();
    const auto candidate_from_exe = (exe_folder / ".." / ".." / ".." / "assets").lexically_normal();
    const auto candidate_from_cwd_fh1 =
        (std::filesystem::current_path() / "FH1" / "assets").lexically_normal();
    const auto candidate_from_cwd =
        (std::filesystem::current_path() / "assets").lexically_normal();

    if (std::filesystem::exists(candidate_from_exe)) {
      paths.game_data_root = candidate_from_exe;
    } else if (std::filesystem::exists(candidate_from_cwd_fh1)) {
      paths.game_data_root = candidate_from_cwd_fh1;
    } else if (std::filesystem::exists(candidate_from_cwd)) {
      paths.game_data_root = candidate_from_cwd;
    }
  }

  void OnPreSetup(rex::RuntimeConfig& config) override {
    config.input_factory = REX_INPUT_BACKEND([](bool) {
      auto input_system = std::make_unique<rex::input::InputSystem>(nullptr);
      input_system->AddDriver(std::make_unique<rex::input::nop::NopInputDriver>(nullptr, 0));
      return input_system;
    });
  }

  void OnPostSetup() override {
    auto* ks = runtime() ? runtime()->kernel_state() : nullptr;
    if (!ks) {
      return;
    }

    constexpr const char* kOptionalModules[] = {
        "game:\\XMediaFacade_default.xex",
        "game:\\SpeechFacade_default.xex",
    };

    for (const char* module_name : kOptionalModules) {
      auto module = ks->LoadUserModule(module_name, false);
      if (module) {
        REXLOG_INFO("Preloaded user module without DllMain attach: {}", module_name);
      } else {
        REXLOG_WARN("Failed to preload optional user module: {}", module_name);
      }
    }
  }
};

REX_DEFINE_APP(forza_horizon_1, ForzaHorizon1App::Create)
